apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grafana
  namespace: monitoring
spec:
  hosts:
    - grafana.dev.innovatshub.com
  gateways:
    - istio-system/innovatshub-dev
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: loki-grafana
            port:
              number: 80